#
# This is free software, lisence use MIT.
# 

####需要设置secrets.ALIDOCKER_KEY####
####阿里云镜像仓库-->访问权限-->固定密码####

name: Bitwarden_rs

on:
  push:
    branches: 
      - master
  schedule:
    - cron: 0 20 * * 1/4

env:
  DOCKER_REGISTRY_USERNAME: xxsxx@aliyun.com	#email
  DOCKER_REGISTRY_HOST: registry.cn-hangzhou.aliyuncs.com
  DOCKER_REGISTRY_URL: registry.cn-hangzhou.aliyuncs.com/docker_latest/bitwarden_rs_arm64    #仓库地址

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master
          fetch-depth: 1000000

      - name: Clone source code
        run:  git clone https://github.com/dani-garcia/bitwarden_rs.git

      - name: Build
        run: |
          cd bitwarden_rs
          rm -rf Dockerfile
          cp ./docker/arm64v8/sqlite/Dockerfile Dockerfile
          echo "$(sed 's/# Builds your dependencies and removes the/Run cargo clean/g' Dockerfile)" > Dockerfile
          sudo docker build -f ./Dockerfile -t bitwarden:latest . 

      - name: Push docker image
        run: |
         sudo docker login --username=$DOCKER_REGISTRY_USERNAME --password=${{ secrets.ALIDOCKER_KEY }}  $DOCKER_REGISTRY_HOST
         echo "============================="
         sudo docker images
         echo "============================="
         ImageId=$(sudo docker images | grep -w 'bitwarden'  | awk '{print $3}')
         echo "============================="
         echo $ImageId
         echo "============================="
         sudo docker tag $ImageId $DOCKER_REGISTRY_URL:latest
         sudo docker push $DOCKER_REGISTRY_URL:latest
